package utils;

import java.awt.Label;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.google.common.collect.Maps;
import org.apache.commons.lang3.time.DateFormatUtils;
import org.apache.commons.lang3.time.DateUtils;
import utils.entity.*;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;

public class StockChanceUtil {


    private static Map<Integer,String> orderTypeMapper = Maps.newHashMap();
    private static Map<Long,String> categoryMapper = Maps.newHashMap();

    static {
        orderTypeMapper.put(0,"项目");
        orderTypeMapper.put(1,"站外-天猫");
        orderTypeMapper.put(2,"站外-拉手");
        orderTypeMapper.put(3,"站外-京东");
        orderTypeMapper.put(4,"站内-直播");
        orderTypeMapper.put(5,"站外-代理");
        orderTypeMapper.put(6,"站内-体验课");
        orderTypeMapper.put(7,"移动端");
        orderTypeMapper.put(8,"学习卡");
        orderTypeMapper.put(9,"外包");
        orderTypeMapper.put(10,"站内-代理");
        orderTypeMapper.put(12,"线下-代理");


        categoryMapper.put(1L,"人力资源管理师");
        categoryMapper.put(2L,"心理咨询师");
        categoryMapper.put(3L,"会计从业资格");
        categoryMapper.put(5L,"法律职业资格考试");
        categoryMapper.put(7L,"注册会计师");
        categoryMapper.put(8L,"证券从业");
        categoryMapper.put(9L,"一级建造师");
        categoryMapper.put(10L,"高级会计职称");
        categoryMapper.put(11L,"公务员");
        categoryMapper.put(12L,"经济师");
        categoryMapper.put(13L,"研究生统一入学考试");
        categoryMapper.put(14L,"初级会计职称");
        categoryMapper.put(15L,"中级会计职称");
        categoryMapper.put(16L,"二级建造师");
        categoryMapper.put(17L,"监理工程师");
        categoryMapper.put(18L,"一级造价工程师");
        categoryMapper.put(19L,"GCT");
        categoryMapper.put(20L,"自考学历");
        categoryMapper.put(21L,"临床执业医师");
        categoryMapper.put(22L,"企业法律顾问");
        categoryMapper.put(23L,"成考");
        categoryMapper.put(24L,"注册税务师");
        categoryMapper.put(25L,"报关员");
        categoryMapper.put(26L,"地方公务员");
        categoryMapper.put(27L,"职称英语");
        categoryMapper.put(28L,"期货从业");
        categoryMapper.put(30L,"远程学历");
        categoryMapper.put(31L,"银行从业");
        categoryMapper.put(32L,"网络营销师");
        categoryMapper.put(33L,"职称计算机");
        categoryMapper.put(34L,"咨询工程师");
        categoryMapper.put(35L,"建筑学院●一级建造师");
        categoryMapper.put(36L,"招标师");
        categoryMapper.put(37L,"护师考试");
        categoryMapper.put(38L,"护士考试");
        categoryMapper.put(39L,"英语四六级");
        categoryMapper.put(40L,"中医执业医师");
        categoryMapper.put(41L,"英语雅思考试");
        categoryMapper.put(42L,"口腔执业医师");
        categoryMapper.put(43L,"公共卫生执业医师");
        categoryMapper.put(44L,"执业药师");
        categoryMapper.put(45L,"物业工程师");
        categoryMapper.put(46L,"保险从业");
        categoryMapper.put(47L,"保险代理人");
        categoryMapper.put(48L,"专本学历");
        categoryMapper.put(49L,"PMP课程");
        categoryMapper.put(100001L,"建造类");
        categoryMapper.put(100002L,"财会类");
        categoryMapper.put(100003L,"学历类");
        categoryMapper.put(100004L,"金融类");
        categoryMapper.put(100005L,"法律类");
        categoryMapper.put(100006L,"英语类");
        categoryMapper.put(100007L,"医师类");
        categoryMapper.put(100008L,"其他");
        categoryMapper.put(100009L,"IT类");
        categoryMapper.put(100011L,"悦成教育");
        categoryMapper.put(100013L,"Android");
        categoryMapper.put(100015L,"安卓");
        categoryMapper.put(100019L,"企业内训类");
        categoryMapper.put(100021L,"临床执业医师");
        categoryMapper.put(100025L,"教师资格证");
        categoryMapper.put(100027L,"教师资格证");
        categoryMapper.put(100029L,"嗨学远程学历");
        categoryMapper.put(100031L,"二级建造师·精品");
        categoryMapper.put(100033L,"信息系统项目管理师");
        categoryMapper.put(100035L,"远程学历余款");
        categoryMapper.put(100037L,"注会西安校区");
        categoryMapper.put(100039L,"人力资源管理师(默认)");
        categoryMapper.put(100041L,"心理咨询师(默认)");
        categoryMapper.put(100043L,"会计从业资格(默认)");
        categoryMapper.put(100045L,"司法考试(默认)");
        categoryMapper.put(100047L,"注册会计师(默认)");
        categoryMapper.put(100049L,"证券从业(默认)");
        categoryMapper.put(100051L,"一级建造师(默认)");
        categoryMapper.put(100053L,"高级会计职称(默认)");
        categoryMapper.put(100055L,"公务员(默认)");
        categoryMapper.put(100057L,"经济师(默认)");
        categoryMapper.put(100059L,"研究生统一入学考试(默认)");
        categoryMapper.put(100061L,"初级会计职称(默认)");
        categoryMapper.put(100063L,"中级会计职称(默认)");
        categoryMapper.put(100065L,"二级建造师(默认)");
        categoryMapper.put(100067L,"监理工程师(默认)");
        categoryMapper.put(100069L,"一级造价工程师(默认)");
        categoryMapper.put(100071L,"GCT(默认)");
        categoryMapper.put(100073L,"自考学历(默认)");
        categoryMapper.put(100075L,"临床执业医师(默认)");
        categoryMapper.put(100077L,"企业法律顾问(默认)");
        categoryMapper.put(100079L,"成考(默认)");
        categoryMapper.put(100081L,"注册税务师(默认)");
        categoryMapper.put(100083L,"报关员(默认)");
        categoryMapper.put(100085L,"地方公务员(默认)");
        categoryMapper.put(100087L,"职称英语(默认)");
        categoryMapper.put(100089L,"期货从业(默认)");
        categoryMapper.put(100091L,"远程学历(默认)");
        categoryMapper.put(100093L,"银行从业(默认)");
        categoryMapper.put(100095L,"网络营销师(默认)");
        categoryMapper.put(100097L,"职称计算机(默认)");
        categoryMapper.put(100099L,"咨询工程师(默认)");
        categoryMapper.put(100101L,"建筑学院●一级建造师(默认)");
        categoryMapper.put(100103L,"招标师(默认)");
        categoryMapper.put(100105L,"护师考试(默认)");
        categoryMapper.put(100107L,"护士考试(默认)");
        categoryMapper.put(100109L,"英语四六级(默认)");
        categoryMapper.put(100111L,"中医执业医师(默认)");
        categoryMapper.put(100113L,"英语雅思考试(默认)");
        categoryMapper.put(100115L,"口腔执业医师(默认)");
        categoryMapper.put(100117L,"公共卫生执业医师(默认)");
        categoryMapper.put(100119L,"执业药师(默认)");
        categoryMapper.put(100121L,"物业工程师(默认)");
        categoryMapper.put(100123L,"保险从业(默认)");
        categoryMapper.put(100125L,"保险代理人(默认)");
        categoryMapper.put(100127L,"专本学历(默认)");
        categoryMapper.put(100129L,"PMP课程(默认)");
        categoryMapper.put(100131L,"悦成教育(默认)");
        categoryMapper.put(100133L,"安卓(默认)");
        categoryMapper.put(100135L,"教师资格证(默认)");
        categoryMapper.put(100137L,"嗨学远程学历(默认)");
        categoryMapper.put(100139L,"二级建造师·精品(默认)");
        categoryMapper.put(100141L,"信息系统项目管理师(默认)");
        categoryMapper.put(100143L,"远程学历余款(默认)");
        categoryMapper.put(100145L,"注会西安校区(默认)");
        categoryMapper.put(100165L,"注册会计师（学则易）");
        categoryMapper.put(100167L,"一级建造师(北京微信)");
        categoryMapper.put(100169L,"一级建造师(上海大区)");
        categoryMapper.put(100171L,"一级建造师(广州大区)");
        categoryMapper.put(100173L,"二级建造师（恒远）");
        categoryMapper.put(100175L,"一级消防工程师");
        categoryMapper.put(100177L,"二级消防工程师");
        categoryMapper.put(100179L,"二级消防工程师（默认）");
        categoryMapper.put(100181L,"一级消防工程师（默认）");
        categoryMapper.put(100183L,"注册会计师（北京）");
        categoryMapper.put(100185L,"一级消防工程师（二建）");
        categoryMapper.put(100187L,"司法考试（秦皇岛）");
        categoryMapper.put(100189L,"一级建造师（恒聚）");
        categoryMapper.put(100191L,"一级建造师（西安）");
        categoryMapper.put(100193L,"二级建造师（西安）");
        categoryMapper.put(100195L,"一级建造师（郑州）");
        categoryMapper.put(100197L,"注册会计师（达州）");
        categoryMapper.put(100199L,"注册会计师（就业）");
        categoryMapper.put(100201L,"司法考试（焦作）");
        categoryMapper.put(100203L,"一级建造师（北京）");
        categoryMapper.put(100205L,"注册会计师（竣亚捷）");
        categoryMapper.put(100207L,"一级建造师（嗨学开放平台）");
        categoryMapper.put(100209L,"二级建造师（嗨学开放平台）");
        categoryMapper.put(100211L,"注册会计师（嗨学开放平台）");
        categoryMapper.put(100213L,"司法考试（嗨学开放平台）");
        categoryMapper.put(100215L,"一级消防工程师（嗨学开放平台）");
        categoryMapper.put(100217L,"执业药师(锦州)");
        categoryMapper.put(100219L,"执业药师（周口）");
        categoryMapper.put(100221L,"司法考试（面授）");
        categoryMapper.put(100223L,"司法考试（哈尔滨）");
        categoryMapper.put(100225L,"注册会计师（长春）");
        categoryMapper.put(100227L,"司法考试（郑州灵豆）");
        categoryMapper.put(100229L,"一级建造师（恒远）");
        categoryMapper.put(100231L,"一级建造师（二建）");
        categoryMapper.put(100233L,"司法考试（承德）");
        categoryMapper.put(100235L,"一级建造师（MVPs）");
        categoryMapper.put(100237L,"一级建造师（石家庄）");
        categoryMapper.put(100239L,"一级建造师（周口）");
        categoryMapper.put(100241L,"司法考试（信阳）");
        categoryMapper.put(100243L,"会计实操");
        categoryMapper.put(100245L,"会计实操");
        categoryMapper.put(100247L,"执业药师（天津）");
        categoryMapper.put(100249L,"执业药师（汉中）");
        categoryMapper.put(100251L,"一级建造师（成都）");
        categoryMapper.put(100253L,"一级建造师（外包）");
        categoryMapper.put(100255L,"一级消防工程师（成都）");
        categoryMapper.put(100257L,"注册会计师（莫名）");
        categoryMapper.put(100259L,"二级建造师（郑州）");
        categoryMapper.put(100261L,"二级建造师（恒聚）");
        categoryMapper.put(100263L,"二级建造师（北京）");
        categoryMapper.put(100265L,"二级建造师（石家庄）");
        categoryMapper.put(100267L,"一级消防工程师（恒聚）");
        categoryMapper.put(100269L,"一级消防工程师（恒远）");
        categoryMapper.put(100271L,"一级消防工程师（郑州）");
        categoryMapper.put(100273L,"一级消防工程师（北京）");
        categoryMapper.put(100275L,"一级消防工程师（周口）");
        categoryMapper.put(100277L,"一级消防工程师（西安）");
        categoryMapper.put(100279L,"一级消防工程师（石家庄）");
        categoryMapper.put(100281L,"司法考试（在线）");
        categoryMapper.put(100283L,"注册会计师（焦作）");
        categoryMapper.put(100285L,"二级建造师（成都）");
        categoryMapper.put(100287L,"一级消防工程师（一建）");
        categoryMapper.put(100289L,"注册会计师（郑州）");
        categoryMapper.put(100291L,"注册会计师（安徽）");
        categoryMapper.put(100293L,"注册会计师（成都翼联）");
        categoryMapper.put(100295L,"二级建造师（周口）");
        categoryMapper.put(100297L,"注册会计师（成都）");
        categoryMapper.put(100299L,"二级建造师（一建）");
        categoryMapper.put(100301L,"二级建造师（外包）");
        categoryMapper.put(100303L,"注册会计师（外包）");
        categoryMapper.put(100305L,"司法考试（外包）");
        categoryMapper.put(100307L,"执业药师（外包）");
        categoryMapper.put(100309L,"司法考试（第16军）");
        categoryMapper.put(100311L,"注册会计师（体验）");
        categoryMapper.put(100313L,"会计从业");
        categoryMapper.put(100315L,"会计从业");
        categoryMapper.put(100317L,"司法考试（竣亚捷）");
        categoryMapper.put(100319L,"司法考试（成绩）");
        categoryMapper.put(100321L,"司法考试（第82军）");
        categoryMapper.put(100323L,"企业内训");
        categoryMapper.put(100325L,"销售");
        categoryMapper.put(100327L,"项目");
        categoryMapper.put(100329L,"运营");
        categoryMapper.put(100331L,"学术");
        categoryMapper.put(100333L,"独立培训");
        categoryMapper.put(100335L,"牛股王");
        categoryMapper.put(100337L,"牛股王（默认）");
        categoryMapper.put(100339L,"司法考试（重庆）");
        categoryMapper.put(100341L,"注册会计师（成都）");
        categoryMapper.put(100343L,"一级建造师(匠建造)");
        categoryMapper.put(100345L,"一级建造师(嗨学课堂)");
        categoryMapper.put(100347L,"二级建造师(匠建造)");
        categoryMapper.put(100349L,"二级建造师(嗨学课堂)");
        categoryMapper.put(100351L,"一级消防工程师（匠建造）");
        categoryMapper.put(100353L,"一级消防工程师（嗨学课堂）");
        categoryMapper.put(100355L,"司法考试（番茄司考）");
        categoryMapper.put(100357L,"司法考试（嗨学课堂）");
        categoryMapper.put(100359L,"注册会计师（嗨学课堂）");
        categoryMapper.put(100361L,"执业药师（嗨学课堂）");
        categoryMapper.put(100363L,"执业药师（百草药师）");
        categoryMapper.put(100365L,"注册会计师（名人堂）");
        categoryMapper.put(100367L,"二级建造师（名人堂）");
        categoryMapper.put(100369L,"执业医师(华医）");
        categoryMapper.put(100371L,"执业医师(华医)");
        categoryMapper.put(100373L,"一级消防工程师（外包）");
        categoryMapper.put(100375L,"执业药师（上海）");
        categoryMapper.put(100377L,"司法考试（名人堂）");
        categoryMapper.put(100379L,"一级消防工程师（名人堂）");
        categoryMapper.put(100381L,"注册会计师（武汉）");
        categoryMapper.put(100383L,"一级建造师（搏扬）");
        categoryMapper.put(100385L,"二级建造师（搏扬）");
        categoryMapper.put(100387L,"一级消防工程师（学则易）");
        categoryMapper.put(100389L,"执业药师（美唐）");
        categoryMapper.put(100391L,"注册会计师（江苏）");
        categoryMapper.put(100393L,"注册会计师（通仁）");
        categoryMapper.put(100395L,"执业药师（顺义）");
        categoryMapper.put(100397L,"执业药师（涿鹿）");
        categoryMapper.put(100399L,"注册会计师（鹤壁）");
        categoryMapper.put(100401L,"注册会计师（周口）");
        categoryMapper.put(100403L,"执业医师（默认）");
        categoryMapper.put(100405L,"执业药师（燕郊）");
        categoryMapper.put(100407L,"执业医师");
        categoryMapper.put(100409L,"执业医师（默认）");
        categoryMapper.put(100411L,"执业助理医师");
        categoryMapper.put(100413L,"执业助理医师（默认）");
        categoryMapper.put(100415L,"执业药师（名人堂）");
        categoryMapper.put(100417L,"一级建造师(高级在线)");
        categoryMapper.put(100419L,"执业药师（山东滨州）");
        categoryMapper.put(100421L,"执业药师（鹤壁）");
        categoryMapper.put(100423L,"执业医师（百草医师）");
        categoryMapper.put(100425L,"执业助理医师（百草医师）");
        categoryMapper.put(100427L,"中级经济师");
        categoryMapper.put(100429L,"中级经济师（默认）");
        categoryMapper.put(100431L,"司法考试（济南）");
        categoryMapper.put(100433L,"一级消防工程师（搏扬）");
        categoryMapper.put(100435L,"中级经济师（郑州）");
        categoryMapper.put(100437L,"测试开发类别「勿用」");
        categoryMapper.put(100439L,"测试开发类别「勿用」");
        categoryMapper.put(100441L,"测试开发类别「勿用」");
        categoryMapper.put(100443L,"傲椒会计");
        categoryMapper.put(100445L,"傲椒会计（北京）");
        categoryMapper.put(100447L,"傲椒会计（成都）");
        categoryMapper.put(100449L,"执业药师（安康）");
        categoryMapper.put(100453L,"中级经济师（邢台）");
        categoryMapper.put(100455L,"执业药师（司法）");
        categoryMapper.put(100457L,"傲椒会计（北京）");
        categoryMapper.put(100459L,"傲椒会计（成都）");
        categoryMapper.put(100461L,"一级消防工程师（表单库）");
        categoryMapper.put(100463L,"成人外教");
        categoryMapper.put(100465L,"成人外教");
        categoryMapper.put(100467L,"中级经济师（承德）");
        categoryMapper.put(100469L,"中级经济师（外包）");
        categoryMapper.put(100471L,"一级消防工程师（建造基础班）");
        categoryMapper.put(100473L,"二级建造师（江苏淮安）");
        categoryMapper.put(100475L,"就业类");
        categoryMapper.put(100477L,"审计就业");
        categoryMapper.put(100479L,"审计就业（默认）");
        categoryMapper.put(100481L,"一级建造师（广州）");
        categoryMapper.put(100483L,"二级建造师（广州）");
        categoryMapper.put(100485L,"一级消防工程师（广州）");
        categoryMapper.put(100487L,"注册会计师（口袋会计）");
        categoryMapper.put(100489L,"初级会计职称（口袋会计）");
        categoryMapper.put(100491L,"会计从业资格（口袋会计）");
        categoryMapper.put(100493L,"注册会计师（司法）");
        categoryMapper.put(100495L,"一级消防工程师（总库）");
        categoryMapper.put(100497L,"注册会计师（司法名人堂）");
        categoryMapper.put(100499L,"注册会计师（成都西沃）");
        categoryMapper.put(100501L,"注册会计师（承德）");
        categoryMapper.put(100503L,"二级建造师（廊坊）");
        categoryMapper.put(100505L,"注册会计师（总库）");
        categoryMapper.put(100507L,"注册会计师（济宁）");
        categoryMapper.put(100509L,"二级建造师（总库）");
        categoryMapper.put(100511L,"一级消防工程师（北京微信）");
        categoryMapper.put(100513L,"注册会计师（药师）");
        categoryMapper.put(100515L,"注册会计师（药师名人堂）");
        categoryMapper.put(100517L,"一级建造师（保定）");
        categoryMapper.put(100519L,"二级建造师（保定）");
        categoryMapper.put(100521L,"一级消防工程师（保定）");
        categoryMapper.put(100523L,"注册会计师（南阳）");
        categoryMapper.put(100525L,"一级建造师（高碑店）");
        categoryMapper.put(100527L,"二级建造师（高碑店）");
        categoryMapper.put(100529L,"一级消防工程师（高碑店）");
        categoryMapper.put(100531L,"一级建造师（重庆路骁）");
        categoryMapper.put(100533L,"一级建造师（赤峰）");
        categoryMapper.put(100535L,"一级建造师（合肥）");
        categoryMapper.put(100537L,"二级建造师（合肥）");
        categoryMapper.put(100539L,"一级建造师（长春）");
        categoryMapper.put(100541L,"二级建造师（长春）");
        categoryMapper.put(100543L,"一级消防工程师（长春）");
        categoryMapper.put(100545L,"一级建造师（安徽格乐）");
        categoryMapper.put(100547L,"二级建造师（安徽格乐）");
        categoryMapper.put(100549L,"一级消防工程师（安徽）");
        categoryMapper.put(100551L,"一级建造师（赤峰德鑫）");
        categoryMapper.put(100553L,"一级建造师（银川）");
        categoryMapper.put(100555L,"一级建造师（成都鸿智）");
        categoryMapper.put(100557L,"一级建造师（四川勤为）");
        categoryMapper.put(100559L,"二级建造师（银川）");
        categoryMapper.put(100561L,"二级建造师（成都鸿智）");
        categoryMapper.put(100563L,"二级建造师（四川勤为）");
        categoryMapper.put(100565L,"司法考试（濮阳）");
        categoryMapper.put(100567L,"司法考试（银川）");
        categoryMapper.put(100569L,"司法考试（北京微信）");
        categoryMapper.put(100571L,"注册会计师（微信）");
        categoryMapper.put(100573L,"一级建造师（菏泽）");
        categoryMapper.put(100575L,"司法考试（四川泽保）");
        categoryMapper.put(100577L,"二级建造师（云南人力帮）");
        categoryMapper.put(100579L,"司法考试（郑州）");
        categoryMapper.put(100581L,"二级建造师（四川西沃）");
        categoryMapper.put(100583L,"一级建造师（涿鹿）");
        categoryMapper.put(100585L,"二级建造师（冠瑞）");
        categoryMapper.put(100587L,"司法考试（四川天翼佳音）");
        categoryMapper.put(100589L,"二级建造师（西安梵天星）");
        categoryMapper.put(100591L,"二级建造师（涿鹿）");
        categoryMapper.put(100593L,"一级建造师（武汉）");
        categoryMapper.put(100595L,"二级建造师（武汉）");
        categoryMapper.put(100597L,"一级消防工程师（成都微信）");
        categoryMapper.put(100599L,"执业药师（嗨学开放平台）");
        categoryMapper.put(100601L,"一级建造师（广州贵华）");
        categoryMapper.put(100603L,"二级建造师（广州贵华）");
        categoryMapper.put(100605L,"司法考试（张家口）");
        categoryMapper.put(100607L,"一级建造师（成都微信）");
        categoryMapper.put(100609L,"司法考试（邢台）");
        categoryMapper.put(100611L,"一级建造师（西安梵天星）");
        categoryMapper.put(100613L,"一级建造师（新余博泰）");
        categoryMapper.put(100615L,"二级建造师（新余博泰）");
        categoryMapper.put(100617L,"一级建造师（北京华建）");
        categoryMapper.put(100619L,"二级建造师（北京华建）");
        categoryMapper.put(100621L,"司法考试（成都微信）");
        categoryMapper.put(100623L,"一级建造师（廊坊）");
        categoryMapper.put(100625L,"一级建造师（四川西沃）");
        categoryMapper.put(100627L,"一级建造师（云南人力帮）");
        categoryMapper.put(100629L,"初级经济师");
        categoryMapper.put(100631L,"初级经济师（默认）");
        categoryMapper.put(100633L,"一级建造师（石家庄超职）");
        categoryMapper.put(100635L,"一级建造师（鼎阳科技）");
        categoryMapper.put(100637L,"一级建造师（重庆美言美行）");
        categoryMapper.put(100639L,"CMA");
        categoryMapper.put(100641L,"CMA(默认)");
        categoryMapper.put(100643L,"注册会计师（石家庄赞皇）");
        categoryMapper.put(100645L,"司法考试（山西长治）");
        categoryMapper.put(100647L,"测试");
        categoryMapper.put(100649L,"一级消防工程师（石家庄超职）");
        categoryMapper.put(100651L,"一级消防工程师(新余博泰)");
        categoryMapper.put(100653L,"一级建造师（广州亚霖）");
        categoryMapper.put(100655L,"二级建造师（广州亚霖）");
        categoryMapper.put(100657L,"司法考试（成都电销）");
        categoryMapper.put(100659L,"一级建造师（企业级）");
        categoryMapper.put(100661L,"二级建造师（企业级）");
        categoryMapper.put(100663L,"一级消防工程师（企业级）");
        categoryMapper.put(100665L,"执业药师（企业级）");
        categoryMapper.put(100667L,"注册会计师（淄博金慧）");
        categoryMapper.put(100669L,"注册会计师（陕西德旭）");
        categoryMapper.put(100671L,"司法考试（独立团）");
        categoryMapper.put(100673L,"司法考试（周口睿宸）");
        categoryMapper.put(100675L,"司法考试（陕西未知星球）");
        categoryMapper.put(100677L,"一级消防工程师（陕西未知星球）");
        categoryMapper.put(100679L,"一级消防工程师（涿鹿）");
        categoryMapper.put(100681L,"注册会计师（济宁创惠）");
        categoryMapper.put(100683L,"一级消防工程师（赤峰）");
        categoryMapper.put(100685L,"一级消防工程师（赤峰德鑫）");
        categoryMapper.put(100687L,"一级消防工程师（廊坊）");
        categoryMapper.put(100689L,"一级消防工程师（重庆美言美行）");
        categoryMapper.put(100691L,"一级消防工程师（西安梵天星）");
        categoryMapper.put(100693L,"注册会计师（CPA预备役）");
        categoryMapper.put(100695L,"注册会计师（天翼佳音）");
        categoryMapper.put(100697L,"二级建造师（徐州宽窄坊）");
        categoryMapper.put(100699L,"二级建造师（佛山）");
        categoryMapper.put(100701L,"二级建造师（漯河和信通）");
        categoryMapper.put(100703L,"二级建造师（正正汇）");
        categoryMapper.put(100705L,"二级建造师（新余）");
        categoryMapper.put(100707L,"一级消防工程师（西安斗米）");
        categoryMapper.put(100709L,"二建考试（济南卓众）");
        categoryMapper.put(100711L,"二级建造师（赤峰汇聚）");
        categoryMapper.put(100713L,"二级建造师（赤峰德鑫）");
        categoryMapper.put(100715L,"二级建造师（广州中汇）");
        categoryMapper.put(100717L,"一级消防工程师（多伦莹信）");
        categoryMapper.put(100719L,"城建培训中心");
        categoryMapper.put(100721L,"二级建造师（重庆和君）");
        categoryMapper.put(100723L,"司法考试（新乡美卓）");
        categoryMapper.put(100725L,"司法考试（衡水世纪）");
        categoryMapper.put(100727L,"二级建造师（成都锐可）");
        categoryMapper.put(100729L,"一级建造师（成都锐可）");
        categoryMapper.put(100731L,"司法考试（保定青木）");
        categoryMapper.put(100733L,"一级消防工程师（湘潭鼎惠）");
        categoryMapper.put(100735L,"测试类别");
        categoryMapper.put(100737L,"一级类别1");
        categoryMapper.put(100739L,"一级类别2");
        categoryMapper.put(100741L,"test");
        categoryMapper.put(100743L,"司法考试（永城厉恒）");
        categoryMapper.put(100745L,"二级建造师（吉安柠檬）");
        categoryMapper.put(100747L,"一级建造师（徐州宽窄坊）");
        categoryMapper.put(100749L,"一级建造师（学习卡库存机会）");
        categoryMapper.put(100751L,"二级建造师（学习卡库存机会）");
        categoryMapper.put(100753L,"司法考试（凌源蓝石）");
        categoryMapper.put(100755L,"司法考试（衡水智臾）");
        categoryMapper.put(100757L,"嗨聊测试类别");
        categoryMapper.put(100759L,"一级消防工程师（四川恰好）");
        categoryMapper.put(100761L,"一级消防工程师（唐山怡安）");
        categoryMapper.put(100763L,"一级建造师（吉安柠檬）");
        categoryMapper.put(100765L,"一级建造师（开放平台线下合作商）");
        categoryMapper.put(100767L,"二级建造师（开放平台线下合作商）");
        categoryMapper.put(100769L,"一级消防工程师（开放平台线下合作商）");
        categoryMapper.put(100771L,"一级造价工程师（开放平台线下合作商）");
        categoryMapper.put(100773L,"初级会计职称（开放平台线下合作商）");
        categoryMapper.put(100775L,"中级会计职称（开放平台线下合作商）");
        categoryMapper.put(100777L,"初级经济师（开放平台线下合作商）");
        categoryMapper.put(100779L,"中级经济师（开放平台线下合作商）");
        categoryMapper.put(100781L,"一级建造师（邯郸恒路）");
        categoryMapper.put(100783L,"一级建造师（枣庄柳泉）");
        categoryMapper.put(100785L,"一级建造师（苏州华旭之）");
        categoryMapper.put(100787L,"一级消防工程师（郑州顺通）");
        categoryMapper.put(100789L,"北京中心销售衔接训");
        categoryMapper.put(100791L,"北京中心销售提升训");
        categoryMapper.put(100793L,"一级建造师（北京中财弘京）");
        categoryMapper.put(100795L,"一级造价工程师（嗨学开放平台）");
        categoryMapper.put(100797L,"一级建造师（邓州往星）");
        categoryMapper.put(100799L,"一级建造师（荆门京建）");
        categoryMapper.put(100801L,"一级建造师（西安分部）");
        categoryMapper.put(100803L,"二级建造师（西安分部）");
        categoryMapper.put(100805L,"一级建造师（河南尚君）");
        categoryMapper.put(100807L,"城建培训中心（默认）");
        categoryMapper.put(100809L,"一级建造师（西安分部）");
        categoryMapper.put(100811L,"二级建造师（西安分部）");
        categoryMapper.put(100813L,"一级消防工程师（成都锐可）");
        categoryMapper.put(100815L,"一级建造师（宝鸡悦知学）");
        categoryMapper.put(100817L,"一级建造师（莱阳朗盛）");
        categoryMapper.put(100819L,"注册会计师（合肥知啊知）");
        categoryMapper.put(100821L,"自考学历（北京微信）");
        categoryMapper.put(100823L,"一级建造师（深圳莘学）");
        categoryMapper.put(100825L,"一级建造师（石家庄明洋）");
        categoryMapper.put(100827L,"一级建造师（邢台文瑞）");
        categoryMapper.put(100829L,"司法考试（潍坊浩辰）");
        categoryMapper.put(100831L,"司法考试（西安分部）");
        categoryMapper.put(100833L,"注册会计师（西安分部）");
        categoryMapper.put(100835L,"二级建造师（河南尚君）");
        categoryMapper.put(100837L,"二级建造师（邯郸恒路）");
        categoryMapper.put(100839L,"二级建造师（石家庄明洋）");
        categoryMapper.put(100841L,"二级建造师（邢台文瑞）");
        categoryMapper.put(100843L,"二级建造师（莱阳朗盛）");
        categoryMapper.put(100845L,"二级建造师(荆门京建)");
        categoryMapper.put(100847L,"二级建造师（北京中财弘京）");
        categoryMapper.put(100849L,"二级建造师（邓州往星）");
        categoryMapper.put(100851L,"二级建造师（宝鸡悦知学）");
        categoryMapper.put(100853L,"二级建造师（南昌博谦）");
        categoryMapper.put(100855L,"二级建造师（合肥华纵）");
        categoryMapper.put(100857L,"二级建造师（天津学泰）");
        categoryMapper.put(100859L,"司法考试（南通新学）");
        categoryMapper.put(100861L,"二级建造师（邵阳湘霸）");
        categoryMapper.put(100863L,"一级消防工程师（北微）");
        categoryMapper.put(100865L,"一级建造师（北京杰玛）");
        categoryMapper.put(100867L,"二级建造师（北京杰玛）");
        categoryMapper.put(100869L,"一级建造师（固安无限）");
        categoryMapper.put(100871L,"二级建造师（固安无限）");
        categoryMapper.put(100873L,"司法考试（濮阳智慧）");
        categoryMapper.put(100875L,"职场技能");
        categoryMapper.put(100877L,"职场技能");
        categoryMapper.put(100879L,"职场技能");
        categoryMapper.put(100881L,"司法考试（沈阳恒晟睿）");
        categoryMapper.put(100883L,"司法考试（淄博软通）");
        categoryMapper.put(100885L,"职场技能（默认）");
        categoryMapper.put(100887L,"中级经济师（嗨学开放平台）");
        categoryMapper.put(100889L,"一级建造师（名人堂）");
        categoryMapper.put(100891L,"一级建造师（名人堂）");
        categoryMapper.put(100893L,"一级建造师（黄埔）");
        categoryMapper.put(100895L,"中级经济师（北京）");
        categoryMapper.put(100897L,"一级消防工程师（名人堂二部）");
        categoryMapper.put(100899L,"中级会计职称（外包）");
        categoryMapper.put(100901L,"中级经济师（焦作）");
        categoryMapper.put(100903L,"一级消防工程师（沧州锦顺）");
        categoryMapper.put(100905L,"二级造价工程师");
        categoryMapper.put(100907L,"二级造价工程师（嗨学开放平台）");
        categoryMapper.put(100909L,"一级消防工程师（荆门京建）");
        categoryMapper.put(100911L,"一级建造师（邵阳湘霸）");
        categoryMapper.put(100913L,"一级建造师（天津学泰）");
        categoryMapper.put(100915L,"一级消防工程师（名人堂三部）");
        categoryMapper.put(100917L,"自考学历（成都微信）");
        categoryMapper.put(100919L,"一级消防工程师（遴选）");
        categoryMapper.put(100921L,"cest");
        categoryMapper.put(100923L,"cest");
        categoryMapper.put(100925L,"注册会计师（射阳砾石）");
        categoryMapper.put(100927L,"一级建造师（辛集恒诺）");
        categoryMapper.put(100929L,"注册会计师（长沙睿驰）");
        categoryMapper.put(100931L,"基础应用专业人才");
        categoryMapper.put(100933L,"基础应用专业人才（外包）");
        categoryMapper.put(100935L,"基础应用专业人才（续报中心）");
        categoryMapper.put(100937L,"基础应用专业人才（政企）");
        categoryMapper.put(100939L,"初级经济师（政企）");
        categoryMapper.put(100941L,"中级经济师（政企）");
        categoryMapper.put(100943L,"工程应用专业人才");
        categoryMapper.put(100945L,"高级应用专业人才");
        categoryMapper.put(100947L,"税务师");
        categoryMapper.put(100949L,"税务师（默认）");
        categoryMapper.put(100951L,"一级建造师（西安中心社群）");
        categoryMapper.put(100953L,"二级建造师（西安中心社群）");
        categoryMapper.put(100955L,"注册会计师（西安中心社群）");
        categoryMapper.put(100957L,"司法考试（西安中心社群）");
        categoryMapper.put(100959L,"心理咨询师");
        categoryMapper.put(100961L,"ACI心理咨询师（遴选）");
        categoryMapper.put(100963L,"一级消防工程师（吉安柠檬）");
        categoryMapper.put(100965L,"ACI心理咨询师（西安中心）（遴选）");
        categoryMapper.put(100967L,"ACI心理咨询师（外包）（遴选）");
        categoryMapper.put(100969L,"心理咨询师（四川德学）(遴选)");
        categoryMapper.put(100971L,"心理咨询师（南京杰越）(遴选)");
        categoryMapper.put(100973L,"心理咨询师（宝鸡悦知学）（遴选）");
        categoryMapper.put(100975L,"一级消防工程师（成都微信）（遴选）");
        categoryMapper.put(100977L,"心理咨询师（苏州华旭之）（遴选）");
        categoryMapper.put(100979L,"心理咨询师（苏州华旭之）（遴选）");
        categoryMapper.put(100981L,"一级造价工程师（外包）");
        categoryMapper.put(100983L,"ACI心理咨询师（成微中心）（遴选）");
        categoryMapper.put(100985L,"心理咨询师（西安梵天星）（遴选）");
        categoryMapper.put(100987L,"ACI心理咨询师（重庆美言美行）(遴选)");
        categoryMapper.put(100989L,"ACI心理咨询师（西安梵天星）（遴选）");
        categoryMapper.put(100991L,"ACI心理咨询师（默认）");
        categoryMapper.put(100993L,"ACI心理咨询师（河南尚君）（遴选）");
        categoryMapper.put(100995L,"注册会计师（有研社群）");
        categoryMapper.put(100997L,"司法考试（有研社群）");
        categoryMapper.put(100999L,"一级建造师（有研社群）");
        categoryMapper.put(101001L,"二级建造师（有研社群）");
        categoryMapper.put(101003L,"注册会计师（大连基地）");
        categoryMapper.put(101005L,"一级消防工程师（成都遴选）");
        categoryMapper.put(101007L,"一级消防工程师（邓州往星）");
        categoryMapper.put(101009L,"一级消防工程师（邓州往星）");
        categoryMapper.put(101011L,"一级消防工程师（深圳莘学）");
        categoryMapper.put(101013L,"一级消防工程师（辛集恒诺）");
        categoryMapper.put(101015L,"一级消防工程师（邢台文瑞）");
        categoryMapper.put(101017L,"一级消防工程师（成都芝麻开门）");
        categoryMapper.put(101019L,"一级消防工程师（河南立之信）");
        categoryMapper.put(101021L,"ACI心理咨询师（永城砺恒）（遴选）");
        categoryMapper.put(101023L,"自考学历（成都）");
        categoryMapper.put(101025L,"健康管理师");
        categoryMapper.put(101027L,"健康管理师（遴选）");
        categoryMapper.put(101029L,"健康管理师（西安中心）（遴选）");
        categoryMapper.put(101031L,"心理咨询师（宿迁智如）（遴选）");
        categoryMapper.put(101033L,"基础应用专业人才（嗨学开放平台）");
        categoryMapper.put(101035L,"ACI心理咨询师（新余成源）（遴选）");
        categoryMapper.put(101037L,"ACI心理咨询师（淄博金慧）（遴选）");
        categoryMapper.put(101039L,"健康管理师（嗨学开放平台）（遴选）");
        categoryMapper.put(101041L,"ACI心理咨询师（泸州九焱）(遴选)");
        categoryMapper.put(101043L,"基础应用专业人才（西安中心）");
        categoryMapper.put(101045L,"工程应用专业人才（西安中心）");
        categoryMapper.put(101047L,"高级应用专业人才（西安中心）");
        categoryMapper.put(101049L,"健康管理师（外包）（遴选）");
        categoryMapper.put(101051L,"注册会计师（淮安嘉行）");
        categoryMapper.put(101053L,"ACI心理咨询师（衡水励弘）（遴选）");
        categoryMapper.put(101055L,"ACI心理咨询师（湖北蓝臣）（遴选）");
        categoryMapper.put(101057L,"ACI心理咨询师（成都微信）（遴选）");
        categoryMapper.put(101059L,"二级建造师（七台河德毅）");
        categoryMapper.put(101061L,"司法考试（菏泽天合）");
        categoryMapper.put(101063L,"一级消防工程师（外包遴选）");
        categoryMapper.put(101065L,"健康管理师（湖北当阳）（遴选）");
        categoryMapper.put(101067L,"健康管理师（江苏淮安）（遴选）");
        categoryMapper.put(101069L,"ACI心理咨询师（邢台宏晟）（遴选）");
        categoryMapper.put(101071L,"二级建造师（辛集恒诺）");
        categoryMapper.put(101073L,"注册会计师（哈尔滨天语）");
        categoryMapper.put(101075L,"ACI心理咨询师（长沙睿驰）（遴选）");
        categoryMapper.put(101077L,"二级建造师（邹城宏禄）");
        categoryMapper.put(101079L,"ACI心理咨询师（徐州步云）（遴选）");
        categoryMapper.put(101081L,"ACI心理咨询师（福州天藻）(遴选)");
        categoryMapper.put(101083L,"基础应用专业人才（名人堂）");
        categoryMapper.put(101085L,"健康管理师（宣化文雅）（遴选）");
        categoryMapper.put(101087L,"营养师");
        categoryMapper.put(101089L,"营养师（西安中心）（遴选）");
        categoryMapper.put(101091L,"健康管理师（沧州朗铭）（遴选）");
        categoryMapper.put(101093L,"中科院心理");
        categoryMapper.put(101095L,"中科院心理（西安中心）（遴选）");
        categoryMapper.put(101097L,"中科院心理（外包）（遴选）");
        categoryMapper.put(101099L,"中科院心理（成都微信）（遴选）");
        categoryMapper.put(101101L,"集结行动（职能新员工培训）");
        categoryMapper.put(101103L,"二级建造师（黑龙江铭烨）");
        categoryMapper.put(101105L,"一级消防工程师（大连文汇）");
        categoryMapper.put(101107L,"初级会计职称（成都微信）（遴选）");
        categoryMapper.put(101109L,"中级会计职称（成都微信）（遴选）");
        categoryMapper.put(101111L,"注册会计师（重庆美音）");
        categoryMapper.put(101113L,"注册会计师（遴选）");
        categoryMapper.put(101115L,"一级消防工程师（成都妙君）");
        categoryMapper.put(101117L,"司法考试（内蒙博约）");
        categoryMapper.put(101119L,"一级消防工程师（成都名人堂）");
        categoryMapper.put(101121L,"二级建造师（江苏步云）");
        categoryMapper.put(101123L,"一级消防工程师（成都名人堂）");
        categoryMapper.put(101125L," 一级消防工程师（泸州九焱）");
        categoryMapper.put(101127L,"初级会计职称（嗨学开放平台）");
        categoryMapper.put(101129L,"二级建造师(钟祥赋硕)");
        categoryMapper.put(101131L,"健康管理师（宿迁智如）（遴选）");
        categoryMapper.put(101133L,"营养师（外包）（遴选）");
        categoryMapper.put(101135L,"营养师（成微中心）（遴选）");
        categoryMapper.put(101137L,"一级建造师（大连文汇）");
        categoryMapper.put(101139L,"心理咨询师（嗨学开放平台）");
        categoryMapper.put(101141L,"消防设施操作员");
        categoryMapper.put(101143L,"消防设施操作员（外包）");
        categoryMapper.put(101145L,"初级消防设施操作员（成微中心）（遴选）");
        categoryMapper.put(101147L,"中级消防设施操作员（成微中心）（遴选）");
        categoryMapper.put(101149L,"ISF心理咨询师");
        categoryMapper.put(101151L,"ISF心理咨询师（外包）（遴选）");
        categoryMapper.put(101153L,"ISF心理咨询师（成微中心）（遴选）");
        categoryMapper.put(101155L,"健康管理师（重庆美言美行）（遴选）");
        categoryMapper.put(101157L,"健康管理师（宝鸡悦知学）");
        categoryMapper.put(101159L,"ISF心理咨询师（西安中心）（遴选）");
        categoryMapper.put(101161L,"健康管理师（成微中心）（遴选）");
        categoryMapper.put(101163L,"院校课程");
        categoryMapper.put(101165L,"院校课程（西南财经大学）");
        categoryMapper.put(101167L,"一级建造师（七台河德毅）");
        categoryMapper.put(101169L,"健康管理师（嗨学开放平台）");
        categoryMapper.put(101171L,"心理咨询师（郑州普智）（遴选）");
        categoryMapper.put(101173L,"一级造价工程师（企业级）");
        categoryMapper.put(101175L,"注册会计师（聊城犀鸟）");
        categoryMapper.put(101177L,"注册会计师（西安佳禾智库）");
        categoryMapper.put(101179L,"司法考试（黄埔）");
        categoryMapper.put(101181L,"心理咨询师（成都昕维）（遴选）");
        categoryMapper.put(101183L,"心理咨询师（成都雒城光年）（遴选）");
        categoryMapper.put(101185L,"一级消防工程师（成都名人堂）");
        categoryMapper.put(101187L,"一级建造师（邹城宏禄）");
        categoryMapper.put(101189L,"健康管理师(交叉营销-西安中心遴选）");
        categoryMapper.put(101191L,"一级建造师（黑龙江铭烨）");
        categoryMapper.put(101193L,"二级建造师（鹤壁金峰）");
        categoryMapper.put(101195L,"健康管理师（聊城飞成）（遴选）");
        categoryMapper.put(101197L,"基础应用专业人才（成微中心）");
        categoryMapper.put(101199L,"二级建造师（邯郸博维）");
        categoryMapper.put(101201L,"心理咨询师（四川其妙）（遴选）");
        categoryMapper.put(101203L,"一级消防工程师（学术中心）");
        categoryMapper.put(101205L,"一级建造师（学术中心）");
        categoryMapper.put(101207L,"二级建造师（学术中心）");
        categoryMapper.put(101209L,"一级造价工程师（学术中心）");
        categoryMapper.put(101211L,"注册会计师（学术中心）");
        categoryMapper.put(101213L,"法律职业资格考试（学术中心）");
        categoryMapper.put(101215L,"ACI心理咨询师（山西恒睿）（遴选）");
        categoryMapper.put(101217L,"注册会计师（山东有光）");
        categoryMapper.put(101219L,"心理咨询师（潍坊语丝）（遴选）");
        categoryMapper.put(101221L,"健康管理师（河南同曌）（遴选）");
        categoryMapper.put(101223L,"二级建造师（邯郸京言）");
        categoryMapper.put(101225L,"心理咨询师（广东银鹏）（遴选）");
        categoryMapper.put(101227L,"心理咨询师（苏州聚合鑫）（遴选）");
        categoryMapper.put(101229L,"一级建造师（天畅新区）");
        categoryMapper.put(101231L,"营养师（遴选）");
        categoryMapper.put(101233L,"心理咨询师（济宁六律）（遴选）");
        categoryMapper.put(101235L,"心理咨询师（西安中心启航）（遴选）");
        categoryMapper.put(101237L,"心理咨询师（西安中心万象）（遴选）");
        categoryMapper.put(101239L,"消防操作员（哥伦布）");
        categoryMapper.put(101241L,"一级消防工程师（西安佳禾智库）");
        categoryMapper.put(101243L,"环保协会");
        categoryMapper.put(101245L,"环保协会（课程培训）");
        categoryMapper.put(101247L,"ISF营养师（沧州朗铭）（遴选）");
        categoryMapper.put(101249L,"一级消防工程师（北海汇学）");
        categoryMapper.put(101251L,"心理咨询师（西安书童）（遴选）");
        categoryMapper.put(101253L,"营养师（西安书童）（遴选）");
        categoryMapper.put(101255L,"消防设施操作员（山西广博）");
        categoryMapper.put(101257L,"理财");
        categoryMapper.put(101259L,"理财（遴选中台）");
        categoryMapper.put(101261L,"一级消防工程师（邢台尚卓）");
        categoryMapper.put(101263L,"test测试类别");
        categoryMapper.put(101265L,"APEI健康管理师");
        categoryMapper.put(101267L,"APEI健康管理师（西安中心遴选）");
        categoryMapper.put(101269L,"APEI健康管理师（外包）(遴选)");
        categoryMapper.put(101271L,"APEI健康管理师（开放平台）");
        categoryMapper.put(101273L,"APEI健康管理师（成微中心）");
    }

    /**
     *
     * @param args
     * @throws Exception
     */
    public static void main(String[] args) throws Exception {
        parseJsonStr();
    }

    private static void parseJsonStr() throws Exception {
        StringBuilder sb = new StringBuilder();
        File file = new File("src/chances.txt");
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String tempString;
            while ((tempString = reader.readLine()) != null) {
                if ("".equals(tempString)) {
                    continue;
                }
                sb.append(tempString);
            }
        }
        List<EsHit> esHits = JSONObject.parseArray(sb.toString(), EsHit.class);
        esHits.stream().map(EsHit::get_source).forEach(ch -> {
            StringBuilder sb1 = new StringBuilder();
            sb1.append(ch.getId()).append("=");
            sb1.append(Objects.nonNull(ch.getLastOrderGoodType())
                    ? orderTypeMapper.get(ch.getLastOrderGoodType()) : "null").append("=");
            sb1.append(Objects.nonNull(ch.getLastOrderCategoryId())
                    ? categoryMapper.get(ch.getLastOrderCategoryId()) : "null").append("=");
            sb1.append(ch.getLastOrderMoney()).append("=");
            if (Objects.isNull(ch.getLastOrderTime())) {
                sb1.append("null").append("=");
            } else {
                sb1.append(DateFormatUtils.format(new Date(ch.getLastOrderTime()), "yyyy-MM-dd HH:mm:ss")).append("=");
            }
            sb1.append(Objects.nonNull(ch.getLoginTotalAmount()) ? ch.getLoginTotalAmount() : "null").append("=");
            if (Objects.isNull(ch.getLastCallTime())) {
                sb1.append("null");
            } else {
                sb1.append(DateFormatUtils.format(new Date(ch.getLastCallTime()), "yyyy-MM-dd HH:mm:ss"));
            }
            System.out.println(sb1);
        });
//        List<Long> chanceIds = esHits.stream().map(ch -> ch.get_source().getId()).collect(Collectors.toList());
//        System.out.println(chanceIds);
//        chanceIds.forEach(System.out::println);
    }

    private static void parseJsonStr2() throws Exception {
        StringBuilder sb = new StringBuilder();
        File file = new File("src/chances.txt");
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String tempString;
            while ((tempString = reader.readLine()) != null) {
                if ("".equals(tempString)) {
                    continue;
                }
                sb.append(tempString);
            }
        }
        List<EsHit> esHits = JSONObject.parseArray(sb.toString(), EsHit.class);
        List<String> chanceIds = esHits.stream().map(ch -> {
            StringBuilder sbMerge = new StringBuilder();
            sbMerge.append(ch.get_source().getId()).append("=");
            sbMerge.append(ch.get_source().getCustomerId()).append("=");
            sbMerge.append(ch.get_source()
                    .getLabels()
                    .stream()
                    .filter(label -> label.getLabelId() == 283)
                    .findAny()
                    .map(LabelInfo::getCreateTime)
                    .map(time -> DateFormatUtils.format(time, "yyyy-MM-dd HH:mm:ss"))
                    .orElse(null)).append("=");
            sbMerge.append(ch.get_source()
                    .getLabels()
                    .stream()
                    .filter(label -> label.getLabelId() == 283)
                    .findAny()
                    .map(LabelInfo::getUpdateTime)
                    .map(time -> DateFormatUtils.format(time, "yyyy-MM-dd HH:mm:ss"))
                    .orElse(null));
            return sbMerge.toString();
        }).collect(Collectors.toList());
        chanceIds.forEach(System.out::println);
    }

    private static void parseAggsJsonStr() throws Exception {
        StringBuilder sb = new StringBuilder();
        File file = new File("src/chances.txt");
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String tempString;
            while ((tempString = reader.readLine()) != null) {
                if ("".equals(tempString)) {
                    continue;
                }
                sb.append(tempString);
            }
        }
        List<AggsEntity> esHits = JSONObject.parseArray(sb.toString(), AggsEntity.class);
        List<String> chanceIds = esHits.stream().map(AggsEntity::getKey).collect(Collectors.toList());
        System.out.println(chanceIds);
    }

    private static void parse12wechatJsonStr() throws Exception {
        StringBuilder sb = new StringBuilder();
        File file = new File("src/chances.txt");
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String tempString;
            while ((tempString = reader.readLine()) != null) {
                if ("".equals(tempString)) {
                    continue;
                }
                sb.append(tempString);
            }
        }
        List<EsHit2> esHits = JSONObject.parseArray(sb.toString(), EsHit2.class);
        List<String> wechates = esHits.stream().map(ch -> ch.get_source().getWechat()).distinct().collect(Collectors.toList());
        wechates.forEach(wechat -> System.out.println("'" + wechat + "',"));
//        chanceIds.forEach(System.out::println);
    }
}
